<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookmark_trip.proto

namespace App\Protos\Trip\V4\TripStatus;

use UnexpectedValueException;

/**
 * Protobuf type <code>trip.v4.TripStatus.Status</code>
 */
class Status
{
    /**
     * Generated from protobuf enum <code>STATUS_UNSPECIFIED = 0;</code>
     */
    const STATUS_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>STATUS_NOT_FOUND = 1;</code>
     */
    const STATUS_NOT_FOUND = 1;
    /**
     * Generated from protobuf enum <code>STATUS_PENDING = 2;</code>
     */
    const STATUS_PENDING = 2;
    /**
     * Generated from protobuf enum <code>STATUS_COMPLETED = 3;</code>
     */
    const STATUS_COMPLETED = 3;

    private static $valueToName = [
        self::STATUS_UNSPECIFIED => 'STATUS_UNSPECIFIED',
        self::STATUS_NOT_FOUND => 'STATUS_NOT_FOUND',
        self::STATUS_PENDING => 'STATUS_PENDING',
        self::STATUS_COMPLETED => 'STATUS_COMPLETED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

