<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookmark_trip.proto

namespace App\Protos\Trip\V4\RecommendActivityRequest;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>trip.v4.RecommendActivityRequest.LocationMeta</code>
 */
class LocationMeta extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional int32 location_id = 1;</code>
     */
    protected $location_id = null;
    /**
     * Generated from protobuf field <code>optional int32 geo_id = 2;</code>
     */
    protected $geo_id = null;
    /**
     * Generated from protobuf field <code>optional double latitude = 3;</code>
     */
    protected $latitude = null;
    /**
     * Generated from protobuf field <code>optional double longitude = 4;</code>
     */
    protected $longitude = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $location_id
     *     @type int $geo_id
     *     @type float $latitude
     *     @type float $longitude
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BookmarkTrip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional int32 location_id = 1;</code>
     * @return int
     */
    public function getLocationId()
    {
        return isset($this->location_id) ? $this->location_id : 0;
    }

    public function hasLocationId()
    {
        return isset($this->location_id);
    }

    public function clearLocationId()
    {
        unset($this->location_id);
    }

    /**
     * Generated from protobuf field <code>optional int32 location_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLocationId($var)
    {
        GPBUtil::checkInt32($var);
        $this->location_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 geo_id = 2;</code>
     * @return int
     */
    public function getGeoId()
    {
        return isset($this->geo_id) ? $this->geo_id : 0;
    }

    public function hasGeoId()
    {
        return isset($this->geo_id);
    }

    public function clearGeoId()
    {
        unset($this->geo_id);
    }

    /**
     * Generated from protobuf field <code>optional int32 geo_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setGeoId($var)
    {
        GPBUtil::checkInt32($var);
        $this->geo_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double latitude = 3;</code>
     * @return float
     */
    public function getLatitude()
    {
        return isset($this->latitude) ? $this->latitude : 0.0;
    }

    public function hasLatitude()
    {
        return isset($this->latitude);
    }

    public function clearLatitude()
    {
        unset($this->latitude);
    }

    /**
     * Generated from protobuf field <code>optional double latitude = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setLatitude($var)
    {
        GPBUtil::checkDouble($var);
        $this->latitude = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double longitude = 4;</code>
     * @return float
     */
    public function getLongitude()
    {
        return isset($this->longitude) ? $this->longitude : 0.0;
    }

    public function hasLongitude()
    {
        return isset($this->longitude);
    }

    public function clearLongitude()
    {
        unset($this->longitude);
    }

    /**
     * Generated from protobuf field <code>optional double longitude = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setLongitude($var)
    {
        GPBUtil::checkDouble($var);
        $this->longitude = $var;

        return $this;
    }

}

