<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookmark_trip.proto

namespace App\Protos\Trip\V4\AffiliateLink;

use UnexpectedValueException;

/**
 * Protobuf type <code>trip.v4.AffiliateLink.Provider</code>
 */
class Provider
{
    /**
     * Generated from protobuf enum <code>PROVIDER_UNSPECIFIED = 0;</code>
     */
    const PROVIDER_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>PROVIDER_KAYAK = 1;</code>
     */
    const PROVIDER_KAYAK = 1;
    /**
     * Generated from protobuf enum <code>PROVIDER_KIWI = 2;</code>
     */
    const PROVIDER_KIWI = 2;
    /**
     * Generated from protobuf enum <code>PROVIDER_TRIP_DOT_COM = 3;</code>
     */
    const PROVIDER_TRIP_DOT_COM = 3;
    /**
     * Generated from protobuf enum <code>PROVIDER_BOOKING = 4;</code>
     */
    const PROVIDER_BOOKING = 4;
    /**
     * Generated from protobuf enum <code>PROVIDER_KLOOK = 5;</code>
     */
    const PROVIDER_KLOOK = 5;
    /**
     * Generated from protobuf enum <code>PROVIDER_VIATOR = 6;</code>
     */
    const PROVIDER_VIATOR = 6;

    private static $valueToName = [
        self::PROVIDER_UNSPECIFIED => 'PROVIDER_UNSPECIFIED',
        self::PROVIDER_KAYAK => 'PROVIDER_KAYAK',
        self::PROVIDER_KIWI => 'PROVIDER_KIWI',
        self::PROVIDER_TRIP_DOT_COM => 'PROVIDER_TRIP_DOT_COM',
        self::PROVIDER_BOOKING => 'PROVIDER_BOOKING',
        self::PROVIDER_KLOOK => 'PROVIDER_KLOOK',
        self::PROVIDER_VIATOR => 'PROVIDER_VIATOR',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

