<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookmark_trip.proto

namespace App\Protos\Trip\V4\HotelRecommendation;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>trip.v4.HotelRecommendation.Hotel</code>
 */
class Hotel extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string description = 2;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>double rating_count = 3;</code>
     */
    protected $rating_count = 0.0;
    /**
     * Generated from protobuf field <code>double stars = 4;</code>
     */
    protected $stars = 0.0;
    /**
     * Generated from protobuf field <code>string stars_text = 5;</code>
     */
    protected $stars_text = '';
    /**
     * Generated from protobuf field <code>repeated string images = 6;</code>
     */
    private $images;
    /**
     * Generated from protobuf field <code>string price = 7;</code>
     */
    protected $price = '';
    /**
     * Generated from protobuf field <code>string url = 8;</code>
     */
    protected $url = '';
    /**
     * Generated from protobuf field <code>repeated .trip.v4.AffiliateLink affliate_links = 9;</code>
     */
    private $affliate_links;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $description
     *     @type float $rating_count
     *     @type float $stars
     *     @type string $stars_text
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $images
     *     @type string $price
     *     @type string $url
     *     @type array<\App\Protos\Trip\V4\AffiliateLink>|\Google\Protobuf\Internal\RepeatedField $affliate_links
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BookmarkTrip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double rating_count = 3;</code>
     * @return float
     */
    public function getRatingCount()
    {
        return $this->rating_count;
    }

    /**
     * Generated from protobuf field <code>double rating_count = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setRatingCount($var)
    {
        GPBUtil::checkDouble($var);
        $this->rating_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double stars = 4;</code>
     * @return float
     */
    public function getStars()
    {
        return $this->stars;
    }

    /**
     * Generated from protobuf field <code>double stars = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setStars($var)
    {
        GPBUtil::checkDouble($var);
        $this->stars = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string stars_text = 5;</code>
     * @return string
     */
    public function getStarsText()
    {
        return $this->stars_text;
    }

    /**
     * Generated from protobuf field <code>string stars_text = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setStarsText($var)
    {
        GPBUtil::checkString($var, True);
        $this->stars_text = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string images = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getImages()
    {
        return $this->images;
    }

    /**
     * Generated from protobuf field <code>repeated string images = 6;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setImages($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->images = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string price = 7;</code>
     * @return string
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>string price = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkString($var, True);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string url = 8;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Generated from protobuf field <code>string url = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .trip.v4.AffiliateLink affliate_links = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAffliateLinks()
    {
        return $this->affliate_links;
    }

    /**
     * Generated from protobuf field <code>repeated .trip.v4.AffiliateLink affliate_links = 9;</code>
     * @param array<\App\Protos\Trip\V4\AffiliateLink>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAffliateLinks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Protos\Trip\V4\AffiliateLink::class);
        $this->affliate_links = $arr;

        return $this;
    }

}

