<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookmark_trip.proto

namespace App\Protos\Trip\V4\Trip;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>trip.v4.Trip.Meta</code>
 */
class Meta extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional .trip.v4.ModelType model_type = 1;</code>
     */
    protected $model_type = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $model_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BookmarkTrip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional .trip.v4.ModelType model_type = 1;</code>
     * @return int
     */
    public function getModelType()
    {
        return isset($this->model_type) ? $this->model_type : 0;
    }

    public function hasModelType()
    {
        return isset($this->model_type);
    }

    public function clearModelType()
    {
        unset($this->model_type);
    }

    /**
     * Generated from protobuf field <code>optional .trip.v4.ModelType model_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setModelType($var)
    {
        GPBUtil::checkEnum($var, \App\Protos\Trip\V4\ModelType::class);
        $this->model_type = $var;

        return $this;
    }

}

