<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookmark_trip.proto

namespace App\Protos\Trip\V4;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>trip.v4.Activity</code>
 */
class Activity extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string local_time = 1;</code>
     */
    protected $local_time = '';
    /**
     * Generated from protobuf field <code>string location = 2;</code>
     */
    protected $location = '';
    /**
     * Generated from protobuf field <code>string city = 3;</code>
     */
    protected $city = '';
    /**
     * Generated from protobuf field <code>string state = 4;</code>
     */
    protected $state = '';
    /**
     * Generated from protobuf field <code>optional double lat = 5;</code>
     */
    protected $lat = null;
    /**
     * Generated from protobuf field <code>optional double lng = 6;</code>
     */
    protected $lng = null;
    /**
     * Generated from protobuf field <code>optional .trip.v4.Activity.LocationType location_type = 7;</code>
     */
    protected $location_type = null;
    /**
     * Generated from protobuf field <code>optional string location_address = 8;</code>
     */
    protected $location_address = null;
    /**
     * Generated from protobuf field <code>optional string operating_hour = 9;</code>
     */
    protected $operating_hour = null;
    /**
     * Generated from protobuf field <code>optional string image_url = 10;</code>
     */
    protected $image_url = null;
    /**
     * Generated from protobuf field <code>double budget_usd = 11;</code>
     */
    protected $budget_usd = 0.0;
    /**
     * Generated from protobuf field <code>uint32 duration_min = 12;</code>
     */
    protected $duration_min = 0;
    /**
     * Generated from protobuf field <code>repeated .trip.v4.ActivityType activity_types = 13;</code>
     */
    private $activity_types;
    /**
     * Generated from protobuf field <code>string description = 14;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>repeated .trip.v4.AffiliateLink affiliate_links = 15;</code>
     */
    private $affiliate_links;
    /**
     * Generated from protobuf field <code>.trip.v4.Activity.LocationMeta location_meta = 16;</code>
     */
    protected $location_meta = null;
    /**
     * Generated from protobuf field <code>string aid = 17;</code>
     */
    protected $aid = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $local_time
     *     @type string $location
     *     @type string $city
     *     @type string $state
     *     @type float $lat
     *     @type float $lng
     *     @type int $location_type
     *     @type string $location_address
     *     @type string $operating_hour
     *     @type string $image_url
     *     @type float $budget_usd
     *     @type int $duration_min
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $activity_types
     *     @type string $description
     *     @type array<\App\Protos\Trip\V4\AffiliateLink>|\Google\Protobuf\Internal\RepeatedField $affiliate_links
     *     @type \App\Protos\Trip\V4\Activity\LocationMeta $location_meta
     *     @type string $aid
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BookmarkTrip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string local_time = 1;</code>
     * @return string
     */
    public function getLocalTime()
    {
        return $this->local_time;
    }

    /**
     * Generated from protobuf field <code>string local_time = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLocalTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->local_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string location = 2;</code>
     * @return string
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Generated from protobuf field <code>string location = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkString($var, True);
        $this->location = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string city = 3;</code>
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Generated from protobuf field <code>string city = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->city = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string state = 4;</code>
     * @return string
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Generated from protobuf field <code>string state = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkString($var, True);
        $this->state = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double lat = 5;</code>
     * @return float
     */
    public function getLat()
    {
        return isset($this->lat) ? $this->lat : 0.0;
    }

    public function hasLat()
    {
        return isset($this->lat);
    }

    public function clearLat()
    {
        unset($this->lat);
    }

    /**
     * Generated from protobuf field <code>optional double lat = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setLat($var)
    {
        GPBUtil::checkDouble($var);
        $this->lat = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double lng = 6;</code>
     * @return float
     */
    public function getLng()
    {
        return isset($this->lng) ? $this->lng : 0.0;
    }

    public function hasLng()
    {
        return isset($this->lng);
    }

    public function clearLng()
    {
        unset($this->lng);
    }

    /**
     * Generated from protobuf field <code>optional double lng = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setLng($var)
    {
        GPBUtil::checkDouble($var);
        $this->lng = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .trip.v4.Activity.LocationType location_type = 7;</code>
     * @return int
     */
    public function getLocationType()
    {
        return isset($this->location_type) ? $this->location_type : 0;
    }

    public function hasLocationType()
    {
        return isset($this->location_type);
    }

    public function clearLocationType()
    {
        unset($this->location_type);
    }

    /**
     * Generated from protobuf field <code>optional .trip.v4.Activity.LocationType location_type = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setLocationType($var)
    {
        GPBUtil::checkEnum($var, Activity\LocationType::class);
        $this->location_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string location_address = 8;</code>
     * @return string
     */
    public function getLocationAddress()
    {
        return isset($this->location_address) ? $this->location_address : '';
    }

    public function hasLocationAddress()
    {
        return isset($this->location_address);
    }

    public function clearLocationAddress()
    {
        unset($this->location_address);
    }

    /**
     * Generated from protobuf field <code>optional string location_address = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setLocationAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->location_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string operating_hour = 9;</code>
     * @return string
     */
    public function getOperatingHour()
    {
        return isset($this->operating_hour) ? $this->operating_hour : '';
    }

    public function hasOperatingHour()
    {
        return isset($this->operating_hour);
    }

    public function clearOperatingHour()
    {
        unset($this->operating_hour);
    }

    /**
     * Generated from protobuf field <code>optional string operating_hour = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setOperatingHour($var)
    {
        GPBUtil::checkString($var, True);
        $this->operating_hour = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string image_url = 10;</code>
     * @return string
     */
    public function getImageUrl()
    {
        return isset($this->image_url) ? $this->image_url : '';
    }

    public function hasImageUrl()
    {
        return isset($this->image_url);
    }

    public function clearImageUrl()
    {
        unset($this->image_url);
    }

    /**
     * Generated from protobuf field <code>optional string image_url = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setImageUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->image_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double budget_usd = 11;</code>
     * @return float
     */
    public function getBudgetUsd()
    {
        return $this->budget_usd;
    }

    /**
     * Generated from protobuf field <code>double budget_usd = 11;</code>
     * @param float $var
     * @return $this
     */
    public function setBudgetUsd($var)
    {
        GPBUtil::checkDouble($var);
        $this->budget_usd = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 duration_min = 12;</code>
     * @return int
     */
    public function getDurationMin()
    {
        return $this->duration_min;
    }

    /**
     * Generated from protobuf field <code>uint32 duration_min = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setDurationMin($var)
    {
        GPBUtil::checkUint32($var);
        $this->duration_min = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .trip.v4.ActivityType activity_types = 13;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getActivityTypes()
    {
        return $this->activity_types;
    }

    /**
     * Generated from protobuf field <code>repeated .trip.v4.ActivityType activity_types = 13;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setActivityTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \App\Protos\Trip\V4\ActivityType::class);
        $this->activity_types = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 14;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .trip.v4.AffiliateLink affiliate_links = 15;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAffiliateLinks()
    {
        return $this->affiliate_links;
    }

    /**
     * Generated from protobuf field <code>repeated .trip.v4.AffiliateLink affiliate_links = 15;</code>
     * @param array<\App\Protos\Trip\V4\AffiliateLink>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAffiliateLinks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Protos\Trip\V4\AffiliateLink::class);
        $this->affiliate_links = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.trip.v4.Activity.LocationMeta location_meta = 16;</code>
     * @return \App\Protos\Trip\V4\Activity\LocationMeta|null
     */
    public function getLocationMeta()
    {
        return $this->location_meta;
    }

    public function hasLocationMeta()
    {
        return isset($this->location_meta);
    }

    public function clearLocationMeta()
    {
        unset($this->location_meta);
    }

    /**
     * Generated from protobuf field <code>.trip.v4.Activity.LocationMeta location_meta = 16;</code>
     * @param \App\Protos\Trip\V4\Activity\LocationMeta $var
     * @return $this
     */
    public function setLocationMeta($var)
    {
        GPBUtil::checkMessage($var, Activity\LocationMeta::class);
        $this->location_meta = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string aid = 17;</code>
     * @return string
     */
    public function getAid()
    {
        return $this->aid;
    }

    /**
     * Generated from protobuf field <code>string aid = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setAid($var)
    {
        GPBUtil::checkString($var, True);
        $this->aid = $var;

        return $this;
    }

}

