<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookmark_trip.proto

namespace App\Protos\Trip\V4;

use UnexpectedValueException;

/**
 * Protobuf type <code>trip.v4.ActivityType</code>
 */
class ActivityType
{
    /**
     * Generated from protobuf enum <code>ACTIVITY_TYPE_UNSPECIFIED = 0;</code>
     */
    const ACTIVITY_TYPE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>ACTIVITY_TYPE_BEACH = 1;</code>
     */
    const ACTIVITY_TYPE_BEACH = 1;
    /**
     * Generated from protobuf enum <code>ACTIVITY_TYPE_SIGHT_SEEING = 2;</code>
     */
    const ACTIVITY_TYPE_SIGHT_SEEING = 2;
    /**
     * Generated from protobuf enum <code>ACTIVITY_TYPE_OUTDOOR_ADVENTURE = 3;</code>
     */
    const ACTIVITY_TYPE_OUTDOOR_ADVENTURE = 3;
    /**
     * Generated from protobuf enum <code>ACTIVITY_TYPE_FESTIVAL_EVENT = 4;</code>
     */
    const ACTIVITY_TYPE_FESTIVAL_EVENT = 4;
    /**
     * Generated from protobuf enum <code>ACTIVITY_TYPE_FOOD_EXPLORATION = 5;</code>
     */
    const ACTIVITY_TYPE_FOOD_EXPLORATION = 5;
    /**
     * Generated from protobuf enum <code>ACTIVITY_TYPE_NIGHTLIFE = 6;</code>
     */
    const ACTIVITY_TYPE_NIGHTLIFE = 6;
    /**
     * Generated from protobuf enum <code>ACTIVITY_TYPE_SHOPPING = 7;</code>
     */
    const ACTIVITY_TYPE_SHOPPING = 7;
    /**
     * Generated from protobuf enum <code>ACTIVITY_TYPE_SPA_WELLNESS = 8;</code>
     */
    const ACTIVITY_TYPE_SPA_WELLNESS = 8;

    private static $valueToName = [
        self::ACTIVITY_TYPE_UNSPECIFIED => 'ACTIVITY_TYPE_UNSPECIFIED',
        self::ACTIVITY_TYPE_BEACH => 'ACTIVITY_TYPE_BEACH',
        self::ACTIVITY_TYPE_SIGHT_SEEING => 'ACTIVITY_TYPE_SIGHT_SEEING',
        self::ACTIVITY_TYPE_OUTDOOR_ADVENTURE => 'ACTIVITY_TYPE_OUTDOOR_ADVENTURE',
        self::ACTIVITY_TYPE_FESTIVAL_EVENT => 'ACTIVITY_TYPE_FESTIVAL_EVENT',
        self::ACTIVITY_TYPE_FOOD_EXPLORATION => 'ACTIVITY_TYPE_FOOD_EXPLORATION',
        self::ACTIVITY_TYPE_NIGHTLIFE => 'ACTIVITY_TYPE_NIGHTLIFE',
        self::ACTIVITY_TYPE_SHOPPING => 'ACTIVITY_TYPE_SHOPPING',
        self::ACTIVITY_TYPE_SPA_WELLNESS => 'ACTIVITY_TYPE_SPA_WELLNESS',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

