<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookmark_trip.proto

namespace App\Protos\Trip\V4;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>trip.v4.AddTripDayActivityRequest</code>
 */
class AddTripDayActivityRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>uint32 days = 2;</code>
     */
    protected $days = 0;
    /**
     * Generated from protobuf field <code>string location_name = 3;</code>
     */
    protected $location_name = '';
    /**
     * Generated from protobuf field <code>string location_address = 4;</code>
     */
    protected $location_address = '';
    /**
     * Generated from protobuf field <code>optional uint32 location_id = 5;</code>
     */
    protected $location_id = null;
    /**
     * Generated from protobuf field <code>optional string place_id = 6;</code>
     */
    protected $place_id = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type int $days
     *     @type string $location_name
     *     @type string $location_address
     *     @type int $location_id
     *     @type string $place_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BookmarkTrip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 days = 2;</code>
     * @return int
     */
    public function getDays()
    {
        return $this->days;
    }

    /**
     * Generated from protobuf field <code>uint32 days = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setDays($var)
    {
        GPBUtil::checkUint32($var);
        $this->days = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string location_name = 3;</code>
     * @return string
     */
    public function getLocationName()
    {
        return $this->location_name;
    }

    /**
     * Generated from protobuf field <code>string location_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLocationName($var)
    {
        GPBUtil::checkString($var, True);
        $this->location_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string location_address = 4;</code>
     * @return string
     */
    public function getLocationAddress()
    {
        return $this->location_address;
    }

    /**
     * Generated from protobuf field <code>string location_address = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setLocationAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->location_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 location_id = 5;</code>
     * @return int
     */
    public function getLocationId()
    {
        return isset($this->location_id) ? $this->location_id : 0;
    }

    public function hasLocationId()
    {
        return isset($this->location_id);
    }

    public function clearLocationId()
    {
        unset($this->location_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 location_id = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setLocationId($var)
    {
        GPBUtil::checkUint32($var);
        $this->location_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string place_id = 6;</code>
     * @return string
     */
    public function getPlaceId()
    {
        return isset($this->place_id) ? $this->place_id : '';
    }

    public function hasPlaceId()
    {
        return isset($this->place_id);
    }

    public function clearPlaceId()
    {
        unset($this->place_id);
    }

    /**
     * Generated from protobuf field <code>optional string place_id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPlaceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->place_id = $var;

        return $this;
    }

}

