<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookmark_trip.proto

namespace App\Protos\Trip\V4;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>trip.v4.AffiliateLink</code>
 */
class AffiliateLink extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.trip.v4.AffiliateLink.Provider provider = 1;</code>
     */
    protected $provider = 0;
    /**
     * Generated from protobuf field <code>string link = 2;</code>
     */
    protected $link = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $provider
     *     @type string $link
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BookmarkTrip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.trip.v4.AffiliateLink.Provider provider = 1;</code>
     * @return int
     */
    public function getProvider()
    {
        return $this->provider;
    }

    /**
     * Generated from protobuf field <code>.trip.v4.AffiliateLink.Provider provider = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setProvider($var)
    {
        GPBUtil::checkEnum($var, AffiliateLink\Provider::class);
        $this->provider = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string link = 2;</code>
     * @return string
     */
    public function getLink()
    {
        return $this->link;
    }

    /**
     * Generated from protobuf field <code>string link = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLink($var)
    {
        GPBUtil::checkString($var, True);
        $this->link = $var;

        return $this;
    }

}

