<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookmark_trip.proto

namespace App\Protos\Trip\V4;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>trip.v4.Bookmark</code>
 */
class Bookmark extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     */
    protected $user_id = '';
    /**
     * Generated from protobuf field <code>repeated .trip.v4.Bookmark.Trip trips = 2;</code>
     */
    private $trips;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $user_id
     *     @type array<\App\Protos\Trip\V4\Bookmark\Trip>|\Google\Protobuf\Internal\RepeatedField $trips
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BookmarkTrip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .trip.v4.Bookmark.Trip trips = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTrips()
    {
        return $this->trips;
    }

    /**
     * Generated from protobuf field <code>repeated .trip.v4.Bookmark.Trip trips = 2;</code>
     * @param array<\App\Protos\Trip\V4\Bookmark\Trip>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTrips($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, Bookmark\Trip::class);
        $this->trips = $arr;

        return $this;
    }

}

