<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookmark_trip.proto

namespace App\Protos\Trip\V4;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>trip.v4.Budget</code>
 */
class Budget extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .trip.v4.Budget.BudgetRecord accommodations = 1;</code>
     */
    private $accommodations;
    /**
     * Generated from protobuf field <code>repeated .trip.v4.Budget.BudgetRecord transportations = 2;</code>
     */
    private $transportations;
    /**
     * Generated from protobuf field <code>repeated .trip.v4.Budget.BudgetRecord foods = 3;</code>
     */
    private $foods;
    /**
     * Generated from protobuf field <code>repeated .trip.v4.Budget.BudgetRecord activities = 4;</code>
     */
    private $activities;
    /**
     * Generated from protobuf field <code>optional string summary = 5;</code>
     */
    protected $summary = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\App\Protos\Trip\V4\Budget\BudgetRecord>|\Google\Protobuf\Internal\RepeatedField $accommodations
     *     @type array<\App\Protos\Trip\V4\Budget\BudgetRecord>|\Google\Protobuf\Internal\RepeatedField $transportations
     *     @type array<\App\Protos\Trip\V4\Budget\BudgetRecord>|\Google\Protobuf\Internal\RepeatedField $foods
     *     @type array<\App\Protos\Trip\V4\Budget\BudgetRecord>|\Google\Protobuf\Internal\RepeatedField $activities
     *     @type string $summary
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BookmarkTrip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .trip.v4.Budget.BudgetRecord accommodations = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAccommodations()
    {
        return $this->accommodations;
    }

    /**
     * Generated from protobuf field <code>repeated .trip.v4.Budget.BudgetRecord accommodations = 1;</code>
     * @param array<\App\Protos\Trip\V4\Budget\BudgetRecord>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAccommodations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, Budget\BudgetRecord::class);
        $this->accommodations = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .trip.v4.Budget.BudgetRecord transportations = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTransportations()
    {
        return $this->transportations;
    }

    /**
     * Generated from protobuf field <code>repeated .trip.v4.Budget.BudgetRecord transportations = 2;</code>
     * @param array<\App\Protos\Trip\V4\Budget\BudgetRecord>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTransportations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, Budget\BudgetRecord::class);
        $this->transportations = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .trip.v4.Budget.BudgetRecord foods = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFoods()
    {
        return $this->foods;
    }

    /**
     * Generated from protobuf field <code>repeated .trip.v4.Budget.BudgetRecord foods = 3;</code>
     * @param array<\App\Protos\Trip\V4\Budget\BudgetRecord>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFoods($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, Budget\BudgetRecord::class);
        $this->foods = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .trip.v4.Budget.BudgetRecord activities = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getActivities()
    {
        return $this->activities;
    }

    /**
     * Generated from protobuf field <code>repeated .trip.v4.Budget.BudgetRecord activities = 4;</code>
     * @param array<\App\Protos\Trip\V4\Budget\BudgetRecord>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setActivities($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, Budget\BudgetRecord::class);
        $this->activities = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string summary = 5;</code>
     * @return string
     */
    public function getSummary()
    {
        return isset($this->summary) ? $this->summary : '';
    }

    public function hasSummary()
    {
        return isset($this->summary);
    }

    public function clearSummary()
    {
        unset($this->summary);
    }

    /**
     * Generated from protobuf field <code>optional string summary = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSummary($var)
    {
        GPBUtil::checkString($var, True);
        $this->summary = $var;

        return $this;
    }

}

