<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookmark_trip.proto

namespace App\Protos\Trip\V4;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>trip.v4.GetBookmarkRequest</code>
 */
class GetBookmarkRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional bool by_me = 1;</code>
     */
    protected $by_me = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $by_me
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BookmarkTrip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional bool by_me = 1;</code>
     * @return bool
     */
    public function getByMe()
    {
        return isset($this->by_me) ? $this->by_me : false;
    }

    public function hasByMe()
    {
        return isset($this->by_me);
    }

    public function clearByMe()
    {
        unset($this->by_me);
    }

    /**
     * Generated from protobuf field <code>optional bool by_me = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setByMe($var)
    {
        GPBUtil::checkBool($var);
        $this->by_me = $var;

        return $this;
    }

}

