<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookmark_trip.proto

namespace App\Protos\Trip\V4;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>trip.v4.HotelRecommendation</code>
 */
class HotelRecommendation extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string title = 1;</code>
     */
    protected $title = '';
    /**
     * Generated from protobuf field <code>string full_title = 2;</code>
     */
    protected $full_title = '';
    /**
     * Generated from protobuf field <code>string from_date = 3;</code>
     */
    protected $from_date = '';
    /**
     * Generated from protobuf field <code>string to_date = 4;</code>
     */
    protected $to_date = '';
    /**
     * Generated from protobuf field <code>string tool_name = 5;</code>
     */
    protected $tool_name = '';
    /**
     * Generated from protobuf field <code>string who = 6;</code>
     */
    protected $who = '';
    /**
     * Generated from protobuf field <code>repeated .trip.v4.HotelRecommendation.Hotel hotels = 7;</code>
     */
    private $hotels;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $title
     *     @type string $full_title
     *     @type string $from_date
     *     @type string $to_date
     *     @type string $tool_name
     *     @type string $who
     *     @type array<\App\Protos\Trip\V4\HotelRecommendation\Hotel>|\Google\Protobuf\Internal\RepeatedField $hotels
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BookmarkTrip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string title = 1;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string full_title = 2;</code>
     * @return string
     */
    public function getFullTitle()
    {
        return $this->full_title;
    }

    /**
     * Generated from protobuf field <code>string full_title = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFullTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->full_title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string from_date = 3;</code>
     * @return string
     */
    public function getFromDate()
    {
        return $this->from_date;
    }

    /**
     * Generated from protobuf field <code>string from_date = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFromDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->from_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string to_date = 4;</code>
     * @return string
     */
    public function getToDate()
    {
        return $this->to_date;
    }

    /**
     * Generated from protobuf field <code>string to_date = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setToDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->to_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tool_name = 5;</code>
     * @return string
     */
    public function getToolName()
    {
        return $this->tool_name;
    }

    /**
     * Generated from protobuf field <code>string tool_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setToolName($var)
    {
        GPBUtil::checkString($var, True);
        $this->tool_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string who = 6;</code>
     * @return string
     */
    public function getWho()
    {
        return $this->who;
    }

    /**
     * Generated from protobuf field <code>string who = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setWho($var)
    {
        GPBUtil::checkString($var, True);
        $this->who = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .trip.v4.HotelRecommendation.Hotel hotels = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHotels()
    {
        return $this->hotels;
    }

    /**
     * Generated from protobuf field <code>repeated .trip.v4.HotelRecommendation.Hotel hotels = 7;</code>
     * @param array<\App\Protos\Trip\V4\HotelRecommendation\Hotel>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHotels($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, HotelRecommendation\Hotel::class);
        $this->hotels = $arr;

        return $this;
    }

}

