<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookmark_trip.proto

namespace App\Protos\Trip\V4;

use UnexpectedValueException;

/**
 * Protobuf type <code>trip.v4.ModelType</code>
 */
class ModelType
{
    /**
     * Generated from protobuf enum <code>MODEL_TYPE_UNSPECIFIED = 0;</code>
     */
    const MODEL_TYPE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>MODEL_TYPE_BARD = 1;</code>
     */
    const MODEL_TYPE_BARD = 1;
    /**
     * Generated from protobuf enum <code>MODEL_TYPE_CHATGPT = 2;</code>
     */
    const MODEL_TYPE_CHATGPT = 2;
    /**
     * Generated from protobuf enum <code>MODEL_TYPE_GEMINI = 3;</code>
     */
    const MODEL_TYPE_GEMINI = 3;

    private static $valueToName = [
        self::MODEL_TYPE_UNSPECIFIED => 'MODEL_TYPE_UNSPECIFIED',
        self::MODEL_TYPE_BARD => 'MODEL_TYPE_BARD',
        self::MODEL_TYPE_CHATGPT => 'MODEL_TYPE_CHATGPT',
        self::MODEL_TYPE_GEMINI => 'MODEL_TYPE_GEMINI',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

