<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookmark_trip.proto

namespace App\Protos\Trip\V4;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>trip.v4.PlanSyncRequest</code>
 */
class PlanSyncRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>.trip.v4.PlanAsyncRequest req = 2;</code>
     */
    protected $req = null;
    /**
     * Generated from protobuf field <code>.trip.v4.PlanSyncRequest.LocationMeta destination_meta = 3;</code>
     */
    protected $destination_meta = null;
    /**
     * Generated from protobuf field <code>optional .trip.v4.PlanSyncRequest.LocationMeta origin_meta = 4;</code>
     */
    protected $origin_meta = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type \App\Protos\Trip\V4\PlanAsyncRequest $req
     *     @type \App\Protos\Trip\V4\PlanSyncRequest\LocationMeta $destination_meta
     *     @type \App\Protos\Trip\V4\PlanSyncRequest\LocationMeta $origin_meta
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BookmarkTrip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.trip.v4.PlanAsyncRequest req = 2;</code>
     * @return \App\Protos\Trip\V4\PlanAsyncRequest|null
     */
    public function getReq()
    {
        return $this->req;
    }

    public function hasReq()
    {
        return isset($this->req);
    }

    public function clearReq()
    {
        unset($this->req);
    }

    /**
     * Generated from protobuf field <code>.trip.v4.PlanAsyncRequest req = 2;</code>
     * @param \App\Protos\Trip\V4\PlanAsyncRequest $var
     * @return $this
     */
    public function setReq($var)
    {
        GPBUtil::checkMessage($var, \App\Protos\Trip\V4\PlanAsyncRequest::class);
        $this->req = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.trip.v4.PlanSyncRequest.LocationMeta destination_meta = 3;</code>
     * @return \App\Protos\Trip\V4\PlanSyncRequest\LocationMeta|null
     */
    public function getDestinationMeta()
    {
        return $this->destination_meta;
    }

    public function hasDestinationMeta()
    {
        return isset($this->destination_meta);
    }

    public function clearDestinationMeta()
    {
        unset($this->destination_meta);
    }

    /**
     * Generated from protobuf field <code>.trip.v4.PlanSyncRequest.LocationMeta destination_meta = 3;</code>
     * @param \App\Protos\Trip\V4\PlanSyncRequest\LocationMeta $var
     * @return $this
     */
    public function setDestinationMeta($var)
    {
        GPBUtil::checkMessage($var, PlanSyncRequest\LocationMeta::class);
        $this->destination_meta = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .trip.v4.PlanSyncRequest.LocationMeta origin_meta = 4;</code>
     * @return \App\Protos\Trip\V4\PlanSyncRequest\LocationMeta|null
     */
    public function getOriginMeta()
    {
        return $this->origin_meta;
    }

    public function hasOriginMeta()
    {
        return isset($this->origin_meta);
    }

    public function clearOriginMeta()
    {
        unset($this->origin_meta);
    }

    /**
     * Generated from protobuf field <code>optional .trip.v4.PlanSyncRequest.LocationMeta origin_meta = 4;</code>
     * @param \App\Protos\Trip\V4\PlanSyncRequest\LocationMeta $var
     * @return $this
     */
    public function setOriginMeta($var)
    {
        GPBUtil::checkMessage($var, PlanSyncRequest\LocationMeta::class);
        $this->origin_meta = $var;

        return $this;
    }

}

