<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookmark_trip.proto

namespace App\Protos\Trip\V4;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>trip.v4.RecommendActivityResponse</code>
 */
class RecommendActivityResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .trip.v4.RecommendActivityResponse.Location locations = 1;</code>
     */
    private $locations;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\App\Protos\Trip\V4\RecommendActivityResponse\Location>|\Google\Protobuf\Internal\RepeatedField $locations
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BookmarkTrip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .trip.v4.RecommendActivityResponse.Location locations = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLocations()
    {
        return $this->locations;
    }

    /**
     * Generated from protobuf field <code>repeated .trip.v4.RecommendActivityResponse.Location locations = 1;</code>
     * @param array<\App\Protos\Trip\V4\RecommendActivityResponse\Location>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLocations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, RecommendActivityResponse\Location::class);
        $this->locations = $arr;

        return $this;
    }

}

