<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookmark_trip.proto

namespace App\Protos\Trip\V4;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>trip.v4.RecommendActivityRequest</code>
 */
class RecommendActivityRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .trip.v4.RecommendActivityRequest.LocationMeta location_metas = 1;</code>
     */
    private $location_metas;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\App\Protos\Trip\V4\RecommendActivityRequest\LocationMeta>|\Google\Protobuf\Internal\RepeatedField $location_metas
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BookmarkTrip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .trip.v4.RecommendActivityRequest.LocationMeta location_metas = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLocationMetas()
    {
        return $this->location_metas;
    }

    /**
     * Generated from protobuf field <code>repeated .trip.v4.RecommendActivityRequest.LocationMeta location_metas = 1;</code>
     * @param array<\App\Protos\Trip\V4\RecommendActivityRequest\LocationMeta>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLocationMetas($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, RecommendActivityRequest\LocationMeta::class);
        $this->location_metas = $arr;

        return $this;
    }

}

