<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookmark_trip.proto

namespace App\Protos\Trip\V4;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>trip.v4.ReoderTripRequest</code>
 */
class ReoderTripRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>repeated .trip.v4.ReoderTripRequest.ReorderDay days = 2;</code>
     */
    private $days;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type array<\App\Protos\Trip\V4\ReoderTripRequest\ReorderDay>|\Google\Protobuf\Internal\RepeatedField $days
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BookmarkTrip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .trip.v4.ReoderTripRequest.ReorderDay days = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDays()
    {
        return $this->days;
    }

    /**
     * Generated from protobuf field <code>repeated .trip.v4.ReoderTripRequest.ReorderDay days = 2;</code>
     * @param array<\App\Protos\Trip\V4\ReoderTripRequest\ReorderDay>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDays($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, ReoderTripRequest\ReorderDay::class);
        $this->days = $arr;

        return $this;
    }

}

