<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookmark_trip.proto

namespace App\Protos\Trip\V4;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>trip.v4.SaveTripRequest</code>
 */
class SaveTripRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>.trip.v4.Trip trip = 2;</code>
     */
    protected $trip = null;
    /**
     * Generated from protobuf field <code>.trip.v4.PlanSyncRequest plan_sync_request = 3;</code>
     */
    protected $plan_sync_request = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type \App\Protos\Trip\V4\Trip $trip
     *     @type \App\Protos\Trip\V4\PlanSyncRequest $plan_sync_request
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BookmarkTrip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.trip.v4.Trip trip = 2;</code>
     * @return \App\Protos\Trip\V4\Trip|null
     */
    public function getTrip()
    {
        return $this->trip;
    }

    public function hasTrip()
    {
        return isset($this->trip);
    }

    public function clearTrip()
    {
        unset($this->trip);
    }

    /**
     * Generated from protobuf field <code>.trip.v4.Trip trip = 2;</code>
     * @param \App\Protos\Trip\V4\Trip $var
     * @return $this
     */
    public function setTrip($var)
    {
        GPBUtil::checkMessage($var, \App\Protos\Trip\V4\Trip::class);
        $this->trip = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.trip.v4.PlanSyncRequest plan_sync_request = 3;</code>
     * @return \App\Protos\Trip\V4\PlanSyncRequest|null
     */
    public function getPlanSyncRequest()
    {
        return $this->plan_sync_request;
    }

    public function hasPlanSyncRequest()
    {
        return isset($this->plan_sync_request);
    }

    public function clearPlanSyncRequest()
    {
        unset($this->plan_sync_request);
    }

    /**
     * Generated from protobuf field <code>.trip.v4.PlanSyncRequest plan_sync_request = 3;</code>
     * @param \App\Protos\Trip\V4\PlanSyncRequest $var
     * @return $this
     */
    public function setPlanSyncRequest($var)
    {
        GPBUtil::checkMessage($var, \App\Protos\Trip\V4\PlanSyncRequest::class);
        $this->plan_sync_request = $var;

        return $this;
    }

}

