<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookmark_trip.proto

namespace App\Protos\Trip\V4;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>trip.v4.TriggerGenerateSitemapRequest</code>
 */
class TriggerGenerateSitemapRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 from = 1;</code>
     */
    protected $from = 0;
    /**
     * Generated from protobuf field <code>int64 to = 2;</code>
     */
    protected $to = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $from
     *     @type int|string $to
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BookmarkTrip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 from = 1;</code>
     * @return int|string
     */
    public function getFrom()
    {
        return $this->from;
    }

    /**
     * Generated from protobuf field <code>int64 from = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFrom($var)
    {
        GPBUtil::checkInt64($var);
        $this->from = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 to = 2;</code>
     * @return int|string
     */
    public function getTo()
    {
        return $this->to;
    }

    /**
     * Generated from protobuf field <code>int64 to = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTo($var)
    {
        GPBUtil::checkInt64($var);
        $this->to = $var;

        return $this;
    }

}

