<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookmark_trip.proto

namespace App\Protos\Trip\V4;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>trip.v4.TripStatus</code>
 */
class TripStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.trip.v4.TripStatus.Status status = 1;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>bool is_private = 2;</code>
     */
    protected $is_private = false;
    /**
     * Generated from protobuf field <code>bool is_owner = 3;</code>
     */
    protected $is_owner = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $status
     *     @type bool $is_private
     *     @type bool $is_owner
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BookmarkTrip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.trip.v4.TripStatus.Status status = 1;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.trip.v4.TripStatus.Status status = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, TripStatus\Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_private = 2;</code>
     * @return bool
     */
    public function getIsPrivate()
    {
        return $this->is_private;
    }

    /**
     * Generated from protobuf field <code>bool is_private = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsPrivate($var)
    {
        GPBUtil::checkBool($var);
        $this->is_private = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_owner = 3;</code>
     * @return bool
     */
    public function getIsOwner()
    {
        return $this->is_owner;
    }

    /**
     * Generated from protobuf field <code>bool is_owner = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsOwner($var)
    {
        GPBUtil::checkBool($var);
        $this->is_owner = $var;

        return $this;
    }

}

