<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookmark_trip.proto

namespace App\Protos\Trip\V4;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>trip.v4.TripDay</code>
 */
class TripDay extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 day = 1;</code>
     */
    protected $day = 0;
    /**
     * Generated from protobuf field <code>repeated .trip.v4.Activity activities = 2;</code>
     */
    private $activities;
    /**
     * Generated from protobuf field <code>string summary = 3;</code>
     */
    protected $summary = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $day
     *     @type array<\App\Protos\Trip\V4\Activity>|\Google\Protobuf\Internal\RepeatedField $activities
     *     @type string $summary
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BookmarkTrip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 day = 1;</code>
     * @return int
     */
    public function getDay()
    {
        return $this->day;
    }

    /**
     * Generated from protobuf field <code>uint32 day = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setDay($var)
    {
        GPBUtil::checkUint32($var);
        $this->day = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .trip.v4.Activity activities = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getActivities()
    {
        return $this->activities;
    }

    /**
     * Generated from protobuf field <code>repeated .trip.v4.Activity activities = 2;</code>
     * @param array<\App\Protos\Trip\V4\Activity>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setActivities($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Protos\Trip\V4\Activity::class);
        $this->activities = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string summary = 3;</code>
     * @return string
     */
    public function getSummary()
    {
        return $this->summary;
    }

    /**
     * Generated from protobuf field <code>string summary = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSummary($var)
    {
        GPBUtil::checkString($var, True);
        $this->summary = $var;

        return $this;
    }

}

