<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookmark_trip.proto

namespace App\Protos\Trip\V4;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>trip.v4.UpdateTripRequest</code>
 */
class UpdateTripRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>optional string title = 2;</code>
     */
    protected $title = null;
    /**
     * Generated from protobuf field <code>optional .google.protobuf.Timestamp travel_at = 3;</code>
     */
    protected $travel_at = null;
    /**
     * Generated from protobuf field <code>optional uint32 days = 4;</code>
     */
    protected $days = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $title
     *     @type \Google\Protobuf\Timestamp $travel_at
     *     @type int $days
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BookmarkTrip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string title = 2;</code>
     * @return string
     */
    public function getTitle()
    {
        return isset($this->title) ? $this->title : '';
    }

    public function hasTitle()
    {
        return isset($this->title);
    }

    public function clearTitle()
    {
        unset($this->title);
    }

    /**
     * Generated from protobuf field <code>optional string title = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .google.protobuf.Timestamp travel_at = 3;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getTravelAt()
    {
        return $this->travel_at;
    }

    public function hasTravelAt()
    {
        return isset($this->travel_at);
    }

    public function clearTravelAt()
    {
        unset($this->travel_at);
    }

    /**
     * Generated from protobuf field <code>optional .google.protobuf.Timestamp travel_at = 3;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setTravelAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->travel_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 days = 4;</code>
     * @return int
     */
    public function getDays()
    {
        return isset($this->days) ? $this->days : 0;
    }

    public function hasDays()
    {
        return isset($this->days);
    }

    public function clearDays()
    {
        unset($this->days);
    }

    /**
     * Generated from protobuf field <code>optional uint32 days = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setDays($var)
    {
        GPBUtil::checkUint32($var);
        $this->days = $var;

        return $this;
    }

}

