<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookmark_trip.proto

namespace App\Protos\Trip\V4\PlanAsyncRequest;

use UnexpectedValueException;

/**
 * Protobuf type <code>trip.v4.PlanAsyncRequest.BudgetType</code>
 */
class BudgetType
{
    /**
     * Generated from protobuf enum <code>BUDGET_TYPE_UNSPECIFIED = 0;</code>
     */
    const BUDGET_TYPE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>BUDGET_TYPE_LOW = 1;</code>
     */
    const BUDGET_TYPE_LOW = 1;
    /**
     * Generated from protobuf enum <code>BUDGET_TYPE_MEDIUM = 2;</code>
     */
    const BUDGET_TYPE_MEDIUM = 2;
    /**
     * Generated from protobuf enum <code>BUDGET_TYPE_HIGH = 3;</code>
     */
    const BUDGET_TYPE_HIGH = 3;

    private static $valueToName = [
        self::BUDGET_TYPE_UNSPECIFIED => 'BUDGET_TYPE_UNSPECIFIED',
        self::BUDGET_TYPE_LOW => 'BUDGET_TYPE_LOW',
        self::BUDGET_TYPE_MEDIUM => 'BUDGET_TYPE_MEDIUM',
        self::BUDGET_TYPE_HIGH => 'BUDGET_TYPE_HIGH',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

