<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookmark_trip.proto

namespace App\Protos\Trip\V4\PlanAsyncRequest;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>trip.v4.PlanAsyncRequest.DietaryRestriction</code>
 */
class DietaryRestriction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool is_halal = 1;</code>
     */
    protected $is_halal = false;
    /**
     * Generated from protobuf field <code>bool is_vegan = 2;</code>
     */
    protected $is_vegan = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $is_halal
     *     @type bool $is_vegan
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BookmarkTrip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool is_halal = 1;</code>
     * @return bool
     */
    public function getIsHalal()
    {
        return $this->is_halal;
    }

    /**
     * Generated from protobuf field <code>bool is_halal = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsHalal($var)
    {
        GPBUtil::checkBool($var);
        $this->is_halal = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_vegan = 2;</code>
     * @return bool
     */
    public function getIsVegan()
    {
        return $this->is_vegan;
    }

    /**
     * Generated from protobuf field <code>bool is_vegan = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsVegan($var)
    {
        GPBUtil::checkBool($var);
        $this->is_vegan = $var;

        return $this;
    }

}

