<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookmark_trip.proto

namespace App\Protos\Trip\V4\PlanAsyncRequest;

use UnexpectedValueException;

/**
 * Protobuf type <code>trip.v4.PlanAsyncRequest.GroupType</code>
 */
class GroupType
{
    /**
     * Generated from protobuf enum <code>GROUP_TYPE_UNSPECIFIED = 0;</code>
     */
    const GROUP_TYPE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>GROUP_TYPE_SOLO = 1;</code>
     */
    const GROUP_TYPE_SOLO = 1;
    /**
     * Generated from protobuf enum <code>GROUP_TYPE_COUPLE = 2;</code>
     */
    const GROUP_TYPE_COUPLE = 2;
    /**
     * Generated from protobuf enum <code>GROUP_TYPE_FAMILY = 3;</code>
     */
    const GROUP_TYPE_FAMILY = 3;
    /**
     * Generated from protobuf enum <code>GROUP_TYPE_FRIEND = 4;</code>
     */
    const GROUP_TYPE_FRIEND = 4;

    private static $valueToName = [
        self::GROUP_TYPE_UNSPECIFIED => 'GROUP_TYPE_UNSPECIFIED',
        self::GROUP_TYPE_SOLO => 'GROUP_TYPE_SOLO',
        self::GROUP_TYPE_COUPLE => 'GROUP_TYPE_COUPLE',
        self::GROUP_TYPE_FAMILY => 'GROUP_TYPE_FAMILY',
        self::GROUP_TYPE_FRIEND => 'GROUP_TYPE_FRIEND',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

