<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookmark_trip.proto

namespace App\Protos\Trip\V4\Activity;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>trip.v4.Activity.LocationMeta</code>
 */
class LocationMeta extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional uint32 location_id = 1;</code>
     */
    protected $location_id = null;
    /**
     * Generated from protobuf field <code>optional uint32 geo_id = 2;</code>
     */
    protected $geo_id = null;
    /**
     * Generated from protobuf field <code>optional string place_id = 3;</code>
     */
    protected $place_id = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $location_id
     *     @type int $geo_id
     *     @type string $place_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BookmarkTrip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 location_id = 1;</code>
     * @return int
     */
    public function getLocationId()
    {
        return isset($this->location_id) ? $this->location_id : 0;
    }

    public function hasLocationId()
    {
        return isset($this->location_id);
    }

    public function clearLocationId()
    {
        unset($this->location_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 location_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLocationId($var)
    {
        GPBUtil::checkUint32($var);
        $this->location_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 geo_id = 2;</code>
     * @return int
     */
    public function getGeoId()
    {
        return isset($this->geo_id) ? $this->geo_id : 0;
    }

    public function hasGeoId()
    {
        return isset($this->geo_id);
    }

    public function clearGeoId()
    {
        unset($this->geo_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 geo_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setGeoId($var)
    {
        GPBUtil::checkUint32($var);
        $this->geo_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string place_id = 3;</code>
     * @return string
     */
    public function getPlaceId()
    {
        return isset($this->place_id) ? $this->place_id : '';
    }

    public function hasPlaceId()
    {
        return isset($this->place_id);
    }

    public function clearPlaceId()
    {
        unset($this->place_id);
    }

    /**
     * Generated from protobuf field <code>optional string place_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPlaceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->place_id = $var;

        return $this;
    }

}

