<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookmark_trip.proto

namespace App\Protos\Trip\V4\Activity;

use UnexpectedValueException;

/**
 * Protobuf type <code>trip.v4.Activity.LocationType</code>
 */
class LocationType
{
    /**
     * Generated from protobuf enum <code>LOCATION_TYPE_UNSPECIFIED = 0;</code>
     */
    const LOCATION_TYPE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>LOCATION_TYPE_CAFE = 1;</code>
     */
    const LOCATION_TYPE_CAFE = 1;
    /**
     * Generated from protobuf enum <code>LOCATION_TYPE_RESTAURANT = 2;</code>
     */
    const LOCATION_TYPE_RESTAURANT = 2;
    /**
     * Generated from protobuf enum <code>LOCATION_TYPE_ATTRACTION = 3;</code>
     */
    const LOCATION_TYPE_ATTRACTION = 3;
    /**
     * Generated from protobuf enum <code>LOCATION_TYPE_HOTEL = 4;</code>
     */
    const LOCATION_TYPE_HOTEL = 4;
    /**
     * Generated from protobuf enum <code>LOCATION_TYPE_MUSEUM = 5;</code>
     */
    const LOCATION_TYPE_MUSEUM = 5;
    /**
     * Generated from protobuf enum <code>LOCATION_TYPE_THINGS_TO_DO = 6;</code>
     */
    const LOCATION_TYPE_THINGS_TO_DO = 6;

    private static $valueToName = [
        self::LOCATION_TYPE_UNSPECIFIED => 'LOCATION_TYPE_UNSPECIFIED',
        self::LOCATION_TYPE_CAFE => 'LOCATION_TYPE_CAFE',
        self::LOCATION_TYPE_RESTAURANT => 'LOCATION_TYPE_RESTAURANT',
        self::LOCATION_TYPE_ATTRACTION => 'LOCATION_TYPE_ATTRACTION',
        self::LOCATION_TYPE_HOTEL => 'LOCATION_TYPE_HOTEL',
        self::LOCATION_TYPE_MUSEUM => 'LOCATION_TYPE_MUSEUM',
        self::LOCATION_TYPE_THINGS_TO_DO => 'LOCATION_TYPE_THINGS_TO_DO',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

