<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bookmark_trip.proto

namespace App\Protos\Trip\V4\Bookmark;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>trip.v4.Bookmark.Trip</code>
 */
class Trip extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string trip_id = 1;</code>
     */
    protected $trip_id = '';
    /**
     * Generated from protobuf field <code>.trip.v4.PlanAsyncRequest plan_request = 2;</code>
     */
    protected $plan_request = null;
    /**
     * Generated from protobuf field <code>string img_url = 3;</code>
     */
    protected $img_url = '';
    /**
     * Generated from protobuf field <code>.trip.v4.Bookmark.Trip.DestinationMeta destination_meta = 4;</code>
     */
    protected $destination_meta = null;
    /**
     * Generated from protobuf field <code>optional string owner_id = 5;</code>
     */
    protected $owner_id = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $trip_id
     *     @type \App\Protos\Trip\V4\PlanAsyncRequest $plan_request
     *     @type string $img_url
     *     @type \App\Protos\Trip\V4\Bookmark\Trip\DestinationMeta $destination_meta
     *     @type string $owner_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BookmarkTrip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string trip_id = 1;</code>
     * @return string
     */
    public function getTripId()
    {
        return $this->trip_id;
    }

    /**
     * Generated from protobuf field <code>string trip_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTripId($var)
    {
        GPBUtil::checkString($var, True);
        $this->trip_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.trip.v4.PlanAsyncRequest plan_request = 2;</code>
     * @return \App\Protos\Trip\V4\PlanAsyncRequest|null
     */
    public function getPlanRequest()
    {
        return $this->plan_request;
    }

    public function hasPlanRequest()
    {
        return isset($this->plan_request);
    }

    public function clearPlanRequest()
    {
        unset($this->plan_request);
    }

    /**
     * Generated from protobuf field <code>.trip.v4.PlanAsyncRequest plan_request = 2;</code>
     * @param \App\Protos\Trip\V4\PlanAsyncRequest $var
     * @return $this
     */
    public function setPlanRequest($var)
    {
        GPBUtil::checkMessage($var, \App\Protos\Trip\V4\PlanAsyncRequest::class);
        $this->plan_request = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string img_url = 3;</code>
     * @return string
     */
    public function getImgUrl()
    {
        return $this->img_url;
    }

    /**
     * Generated from protobuf field <code>string img_url = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setImgUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->img_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.trip.v4.Bookmark.Trip.DestinationMeta destination_meta = 4;</code>
     * @return \App\Protos\Trip\V4\Bookmark\Trip\DestinationMeta|null
     */
    public function getDestinationMeta()
    {
        return $this->destination_meta;
    }

    public function hasDestinationMeta()
    {
        return isset($this->destination_meta);
    }

    public function clearDestinationMeta()
    {
        unset($this->destination_meta);
    }

    /**
     * Generated from protobuf field <code>.trip.v4.Bookmark.Trip.DestinationMeta destination_meta = 4;</code>
     * @param \App\Protos\Trip\V4\Bookmark\Trip\DestinationMeta $var
     * @return $this
     */
    public function setDestinationMeta($var)
    {
        GPBUtil::checkMessage($var, Trip\DestinationMeta::class);
        $this->destination_meta = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string owner_id = 5;</code>
     * @return string
     */
    public function getOwnerId()
    {
        return isset($this->owner_id) ? $this->owner_id : '';
    }

    public function hasOwnerId()
    {
        return isset($this->owner_id);
    }

    public function clearOwnerId()
    {
        unset($this->owner_id);
    }

    /**
     * Generated from protobuf field <code>optional string owner_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setOwnerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->owner_id = $var;

        return $this;
    }

}

